### PR TITLE
[CJP-7913] JVM settings for astro repositories

### PR DESCRIPTION
**Pull request by varmenise**
@reviewbybees @cloudbees/team-astro

### CODE REVIEW

**Comment by batmat** [comment]
No PR build kicked in?!

**Comment by batmat** [comment]
Filed https://cloudbees.atlassian.net/browse/OPS-3080

**Comment by bwalding** [comment]
Fixed permissions and re-ran PR build - all blue.

**Review by batmat — APPROVED** [review]
:bee:

**Comment by batmat** [comment]
So Blue. Thanks Ben.

**Pull request merged**
